import { flattenDocument } from './flatten';
import { assertValidTokenDocuments, validateTokenDocuments } from './validate';
import {
  type FlattenedToken,
  type TokenDocument,
  type TokenRecords,
  type TokenRegistry,
  type TokenNode,
  type TokenValue,
} from './types';

type Register = 'marketing' | 'product';

const aliasFor = (value: TokenValue): string | undefined => {
  if (typeof value !== 'string') {
    return undefined;
  }

  return /^\{([^{}]+)\}$/.exec(value)?.[1];
};

const allTokens = (records: TokenRecords): readonly FlattenedToken[] => [
  ...flattenDocument(records.primitives, ['primitives']),
  ...flattenDocument(records.product.common, ['product', 'common']),
  ...flattenDocument(records.product.light, ['product', 'light']),
  ...flattenDocument(records.product.dark, ['product', 'dark']),
  ...flattenDocument(records.marketing.common, ['marketing', 'common']),
  ...flattenDocument(records.marketing.light, ['marketing', 'light']),
  ...flattenDocument(records.marketing.muted, ['marketing', 'muted']),
  ...flattenDocument(records.marketing.dark, ['marketing', 'dark']),
];

const resolveValues = (tokens: readonly FlattenedToken[]) => {
  const byPath = new Map(tokens.map((token) => [token.path, token]));
  const resolved = new Map<string, TokenValue>();

  const resolve = (path: string): TokenValue => {
    const cached = resolved.get(path);
    if (cached !== undefined) {
      return cached;
    }

    const token = byPath.get(path);
    if (!token) {
      throw new Error(`Cannot resolve missing token ${path}`);
    }

    const alias = aliasFor(token.value);
    const value = alias ? resolve(alias) : token.value;
    resolved.set(path, value);
    return value;
  };

  for (const token of tokens) {
    resolve(token.path);
  }

  return Object.fromEntries(resolved);
};

export const compileTokenRegistry = (records: TokenRecords): TokenRegistry => {
  assertValidTokenDocuments(records);
  const tokens = allTokens(records);

  return {
    source: records,
    tokens,
    values: resolveValues(tokens),
  };
};

const formatValue = (value: TokenValue): string => {
  if (typeof value === 'object' && value !== null && 'value' in value) {
    const dimension = value as { value: number; unit: string };
    return `${dimension.value}${dimension.unit}`;
  }

  if (typeof value === 'object') {
    return JSON.stringify(value);
  }

  return String(value);
};

const sourcePathFor = (token: FlattenedToken, register: Register): string => {
  const prefix = `${register}.`;
  const path = token.path.slice(prefix.length);
  const modeSeparator = path.indexOf('.');
  return path.slice(modeSeparator + 1);
};

const cssVariableNameFor = (
  token: FlattenedToken,
  register: Register,
): string => {
  const path = sourcePathFor(token, register)
    .split('.')
    .map((segment) =>
      segment.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`),
    )
    .join('-');
  return register === 'product' ? `--t-${path}` : `--t-marketing-${path}`;
};

const tokensForMode = (
  registry: TokenRegistry,
  register: Register,
  mode: string,
) =>
  registry.tokens
    .filter(
      (token) =>
        token.path.startsWith(`${register}.common.`) ||
        token.path.startsWith(`${register}.${mode}.`),
    )
    .sort((left, right) => left.path.localeCompare(right.path));

const modeClass = (register: Register, mode: string) =>
  register === 'product' ? `.${mode}` : `.marketing-${mode}`;

export const renderCss = (registry: TokenRegistry, register: Register) => {
  const modes =
    register === 'product' ? ['light', 'dark'] : ['light', 'muted', 'dark'];
  const lines = [
    '/* Generated by twenty-design-tokens. Do not edit manually. */',
  ];

  for (const mode of modes) {
    lines.push(`${modeClass(register, mode)} {`);
    for (const token of tokensForMode(registry, register, mode)) {
      const value = registry.values[token.path];
      lines.push(
        `  ${cssVariableNameFor(token, register)}: ${formatValue(value)};`,
      );
    }
    lines.push('}', '');
  }

  return `${lines.join('\n').trim()}\n`;
};

const insertNested = (
  target: Record<string, unknown>,
  path: string,
  value: string,
) => {
  const parts = path.split('.');
  let current = target;

  for (const part of parts.slice(0, -1)) {
    const next = current[part];
    if (typeof next !== 'object' || next === null) {
      current[part] = {};
    }
    current = current[part] as Record<string, unknown>;
  }

  current[parts[parts.length - 1] ?? path] = value;
};

export const renderTypeScript = (
  registry: TokenRegistry,
  register: Register,
) => {
  const mode = register === 'product' ? 'light' : 'light';
  const accessors: Record<string, unknown> = {};

  for (const token of tokensForMode(registry, register, mode)) {
    insertNested(
      accessors,
      sourcePathFor(token, register),
      `var(${cssVariableNameFor(token, register)})`,
    );
  }

  const variableName = `${register}CssVariables`;
  return [
    '/* Generated by twenty-design-tokens. Do not edit manually. */',
    `export const ${variableName} = ${JSON.stringify(accessors, null, 2)} as const;`,
    '',
  ].join('\n');
};

const sortedDocument = (document: TokenDocument): TokenDocument => {
  const sorted: Record<string, TokenDocument | TokenNode> = {};
  for (const key of Object.keys(document).sort()) {
    const value = document[key];
    sorted[key] = '$value' in value ? value : sortedDocument(value);
  }
  return sorted;
};

export const renderFigmaBundle = (
  registry: TokenRegistry,
  register: Register,
) => {
  const source =
    register === 'marketing'
      ? registry.source.marketing
      : registry.source.product;
  const bundle = {
    $description: `${register} visual register generated from the canonical DTCG source.`,
    $schema: 'https://design-tokens.github.io/community-group/format/',
    common: sortedDocument(source.common),
    dark: sortedDocument(source.dark),
    light: sortedDocument(source.light),
    primitives: sortedDocument(registry.source.primitives),
    ...(register === 'marketing'
      ? { muted: sortedDocument(registry.source.marketing.muted) }
      : {}),
  };

  return `${JSON.stringify(bundle, null, 2)}\n`;
};

export { validateTokenDocuments };
