import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { compileTokenRegistry, renderCss } from './compiler';
import { tokenRecords } from './source-records';

const legacyThemePath = (mode: 'dark' | 'light') =>
  resolve(
    import.meta.dirname,
    '../../../twenty-ui/src/theme-constants',
    `theme-${mode}.css`,
  );

const normalize = (value: string) => value.replace(/\s+/g, ' ').trim();

const readVariable = (
  css: string,
  variableName: string,
): string | undefined => {
  const escapedName = variableName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const match = new RegExp(
    `${escapedName}:\\s*([\\s\\S]*?);\\s*(?=--t-|\\}|$)`,
  ).exec(css);
  return match?.[1] ? normalize(match[1]) : undefined;
};

const readModeBlock = (css: string, mode: 'dark' | 'light'): string => {
  const block = new RegExp(`\\.${mode}\\s*\\{([\\s\\S]*?)\\n\\}`).exec(css);
  return block?.[1] ?? '';
};

const readDeclarations = (css: string): Record<string, string> => {
  const declarations: Record<string, string> = {};
  const declarationPattern = /(--t-[\w-]+):\s*([\s\S]*?);(?=\s*--t-|\s*})/g;

  for (const match of css.matchAll(declarationPattern)) {
    const variableName = match[1];
    const variableValue = match[2];
    if (variableName && variableValue) {
      declarations[variableName] = normalize(variableValue);
    }
  }

  return Object.fromEntries(
    Object.entries(declarations).sort(([left], [right]) =>
      left.localeCompare(right),
    ),
  );
};

export const readLegacyThemeManifest = () => ({
  dark: readDeclarations(readFileSync(legacyThemePath('dark'), 'utf8')),
  light: readDeclarations(readFileSync(legacyThemePath('light'), 'utf8')),
});

export const renderLegacyThemeManifest = () =>
  `${JSON.stringify(readLegacyThemeManifest(), null, 2)}\n`;

export const renderLegacyCssVariableReferences = () => {
  const manifest = readLegacyThemeManifest();
  const names = Object.keys(manifest.light);
  const references = Object.fromEntries(
    names.map((name) => [name, `var(${name})`]),
  );

  return [
    '/* Generated by twenty-design-tokens. Do not edit manually. */',
    `export const legacyCssVariableReferences = ${JSON.stringify(references, null, 2)} as const;`,
    '',
  ].join('\n');
};

const legacyVariables = [
  '--t-animation-duration-fast',
  '--t-background-primary',
  '--t-background-secondary',
  '--t-border-color-light',
  '--t-border-color-medium',
  '--t-border-radius-sm',
  '--t-font-color-primary',
  '--t-font-color-secondary',
  '--t-font-family',
  '--t-font-size-sm',
  '--t-icon-size-md',
  '--t-last-layer-z-index',
  '--t-spacing-multiplicator',
];

export const getLegacyParityVariableError = (
  mode: 'dark' | 'light',
  variableName: string,
  legacyValue: string | undefined,
  generatedValue: string | undefined,
): string | undefined => {
  if (legacyValue === undefined) {
    return `${mode} legacy CSS is missing ${variableName}`;
  }

  if (generatedValue === undefined) {
    return `${mode} generated CSS is missing ${variableName}`;
  }

  if (legacyValue !== generatedValue) {
    return `${mode} ${variableName} changed from ${legacyValue} to ${generatedValue}`;
  }

  return undefined;
};

export const checkLegacyParity = (): readonly string[] => {
  const registry = compileTokenRegistry(tokenRecords);
  const errors: string[] = [];

  for (const mode of ['light', 'dark'] as const) {
    const css = readModeBlock(
      readFileSync(legacyThemePath(mode), 'utf8'),
      mode,
    );
    const generated = readModeBlock(renderCss(registry, 'product'), mode);

    for (const variableName of legacyVariables) {
      const legacyValue = readVariable(css, variableName);
      const generatedValue = readVariable(generated, variableName);

      const error = getLegacyParityVariableError(
        mode,
        variableName,
        legacyValue,
        generatedValue,
      );

      if (error) {
        errors.push(error);
      }
    }
  }

  return errors;
};
