export const LICITACIONES_STAGING_COLUMN_MAP: Record<string, string[]> = {
  codigo_externo: ['CodigoExterno'],
  codigo: ['Codigo'],
  codigoitem: ['Codigoitem'],
  codigo_proveedor: ['CodigoProveedor'],
  rut_proveedor: ['RutProveedor'],
  nombre_de_la_oferta: ['Nombre de la Oferta'],
  estado_oferta: ['Estado Oferta'],
  oferta_seleccionada: ['Oferta seleccionada'],
  cantidad_ofertada: ['Cantidad Ofertada'],
  valor_total_ofertado: ['Valor Total Ofertado'],
  tipo_de_adquisicion: ['Tipo de Adquisicion'],
  fecha_publicacion: ['FechaPublicacion'],
  fecha_adjudicacion: ['FechaAdjudicacion'],
  estado: ['Estado'],
  nombre_unidad: ['NombreUnidad'],
  nombre_producto_generico: [
    'Nombre producto genrico',
    'Nombre producto genérico',
    'Nombre producto generico',
    'Genérico',
    'Generico',
  ],
  cantidad_adjudicada: ['CantidadAdjudicada'],
  monto_estimado_adjudicado: ['Monto Estimado Adjudicado'],
};
