export const OC_STAGING_COLUMN_MAP: Record<string, string[]> = {
  codigo: ['Codigo'],
  source_id: ['ID'],
  iditem: ['IDItem'],
  codigo_licitacion: ['CodigoLicitacion'],
  fecha_envio: ['FechaEnvio'],
  estado: ['Estado'],
  descripcion_tipo_oc: ['DescripcionTipoOC'],
  codigo_abreviado_tipo_oc: ['CodigoAbreviadoTipoOC'],
  codigo_tipo: ['CodigoTipo'],
  tipo_moneda_oc: ['TipoMonedaOC'],
  monto_total_oc_pesos_chilenos: ['MontoTotalOC_PesosChilenos'],
  impuestos_oc: ['ImpuestosOC'],
  unidad_compra: ['UnidadCompra'],
  nombre_proveedor: ['NombreProveedor'],
  codigo_producto_onu: ['CodigoProductoONU'],
  total_linea_neto: ['TotalLineaNeto'],
  es_compra_agil: ['EsCompraAgil'],
  es_trato_directo: ['EsTratoDirecto'],
  forma_de_pago: ['Forma de Pago'],
  codigo_convenio_marco: ['Codigo_ConvenioMarco'],
};
